name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build project
        run: |
          npx -y mdpdf readme.md cv.pdf --style=style.css --gh-style
          npx -y mdpdf readme-spanish.md "cv-spanish.pdf" --style=style.css --gh-style

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv.pdf
            cv-spanish.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
